export const CONSTANTS = {
	COMPANY_FETCH_START: 'COMPANY_FETCH_START',
	COMPANY_FETCH_SUCCESS: 'COMPANY_FETCH_SUCCESS',
	COMPANY_FETCH_ERROR: 'COMPANY_FETCH_ERROR',

	SIGNUP_START: 'SIGNUP_START',
	SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
	SIGNUP_ERROR: 'SIGNUP_ERROR',

	SIGNIN_START: 'SIGNIN_START',
	SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
	SIGNIN_ERROR: 'SIGNIN_ERROR' ,

	SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
	SIGNOUT_ERROR: 'SIGNOUT_ERROR',

	GET_USER_START: 'GET_USER_START',
	GET_USER_SUCCESS : 'GET_USER_SUCCESS',
	GET_USER_ERROR: 'GET_USER_ERROR',

	SET_TOKEN_IN_STORE_START: 'SET_TOKEN_IN_STORE_START',
	SET_TOKEN_IN_STORE_SUCCESS: 'SET_TOKEN_IN_STORE_SUCCESS',

	REMOVE_TOKEN_IN_STORE: 'REMOVE_TOKEN_IN_STORE',

	EDIT_USER_START: 'EDIT_USER_START',
	EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
	EDIT_USER_ERROR: 'EDIT_USER_ERROR',

	GET_TOPICS_START: 'GET_TOPICS_START',
	GET_TOPICS_SUCCESS: 'GET_TOPICS_SUCCESS',
	GET_TOPICS_ERROR: 'GET_TOPICS_ERROR',

	ADD_TOPIC_START: 'ADD_TOPIC_START',
	ADD_TOPIC_SUCCESS: 'ADD_TOPIC_SUCCESS',
	ADD_TOPIC_ERROR: 'ADD_TOPIC_ERROR',

	DELETE_TOPIC_SUCCESS: 'DELETE_TOPIC_SUCCESS',
	DELETE_TOPIC_ERROR: 'DELETE_TOPIC_ERROR',

	GET_PROJECTS_START: 'GET_PROJECTS_START',
	GET_PROJECTS_SUCCESS: 'GET_PROJECTS_SUCCESS',
	GET_PROJECTS_ERROR: 'GET_PROJECTS_ERROR',

	GET_TEAMS_START: 'GET_TEAMS_START',
	GET_TEAMS_SUCCESS: 'GET_TEAMS_SUCCESS',
	GET_TEAMS_ERROR: 'GET_TEAMS_ERROR'

}

export const URL = 'https://picsart-bootcamp-2020-api.herokuapp.com/api/v1'